name: "Vprofile Terraform IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - "terraform/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"

env:
  #Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # S3 bucket for terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: "us-east-1"
  EKSCLUSTER: "gitops-eks"

jobs:
  terraform:
    name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v6

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        # with:
        #   terraform_version: 1.1.7

      - name: "Terraform Init"
        id: init
        # working-directory: ./terraform
        run: terraform init -backend-config="bucket=${{ env.BUCKET_TF_STATE }}" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: "Terraform Plan"
        working-directory: ./terraform
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Terraform plan failed. Please check the plan output for details."
          exit 1

      # - name: "Terraform Apply"
      #   if: github.ref == 'refs/heads/main'
      #   working-directory: ./terraform
      #   run: terraform apply -auto-approve
